// 
// Code generated by a template.
//
using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;

namespace CCLLC.CDS.Sdk.Metadata.Proxy 
{

	[EntityLogicalNameAttribute("sdkmessageresponse")]
	public partial class SdkMessageResponse : Entity
	{
		public static string EntityLogicalName => "sdkmessageresponse";

		public SdkMessageResponse()
			: base("sdkmessageresponse")
		{
		}

		#region Late Bound Fields
	
		public class Fields
		{			
			public const string Id = "sdkmessageresponseid";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CustomizationLevel = "customizationlevel";
			public const string IntroducedVersion = "introducedversion";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string SdkMessageRequestId = "sdkmessagerequestid";
			public const string SdkMessageResponseId = "sdkmessageresponseid";
			public const string SdkMessageResponseIdUnique = "sdkmessageresponseidunique";
			public const string SolutionId = "solutionid";
			public const string SupportingSolutionId = "supportingsolutionid";
			public const string VersionNumber = "versionnumber";
		}

		#endregion

		[AttributeLogicalNameAttribute("sdkmessageresponseid")]
		public override Guid Id
		{
			get { return base.Id; }
			set { SdkMessageResponseId = value; }
		}

		[AttributeLogicalNameAttribute("componentstate")]
		public virtual OptionSetValue ComponentState
		{
			get { return this.GetAttributeValue<OptionSetValue>("componentstate"); }
		}
		[AttributeLogicalNameAttribute("createdby")]
		public virtual EntityReference CreatedBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdby"); }
		}
		[AttributeLogicalNameAttribute("createdon")]
		public virtual DateTime? CreatedOn
		{
			get { return this.GetAttributeValue<DateTime?>("createdon"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfby")]
		public virtual EntityReference CreatedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public virtual string CreatedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public virtual string CreatedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("customizationlevel")]
		public virtual int? CustomizationLevel
		{
			get { return this.GetAttributeValue<int?>("customizationlevel"); }
		}
		[AttributeLogicalNameAttribute("introducedversion")]
		public virtual string IntroducedVersion
		{
			get { return this.GetAttributeValue<string>("introducedversion"); }
			set { this.SetAttributeValue("introducedversion", value); }
		}
		[AttributeLogicalNameAttribute("ismanaged")]
		public virtual bool? IsManaged
		{
			get { return this.GetAttributeValue<bool?>("ismanaged"); }
		}
		[AttributeLogicalNameAttribute("ismanagedname")]
		public virtual string IsManagedName
		{
			get { return this.GetAttributeValue<string>("ismanagedname"); }
		}
		[AttributeLogicalNameAttribute("modifiedby")]
		public virtual EntityReference ModifiedBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedby"); }
		}
		[AttributeLogicalNameAttribute("modifiedon")]
		public virtual DateTime? ModifiedOn
		{
			get { return this.GetAttributeValue<DateTime?>("modifiedon"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public virtual EntityReference ModifiedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public virtual string ModifiedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public virtual string ModifiedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("organizationid")]
		public virtual EntityReference OrganizationId
		{
			get { return this.GetAttributeValue<EntityReference>("organizationid"); }
		}
		[AttributeLogicalNameAttribute("overwritetime")]
		public virtual DateTime? OverwriteTime
		{
			get { return this.GetAttributeValue<DateTime?>("overwritetime"); }
		}
		[AttributeLogicalNameAttribute("sdkmessagerequestid")]
		public virtual EntityReference SdkMessageRequestId
		{
			get { return this.GetAttributeValue<EntityReference>("sdkmessagerequestid"); }
		}
		[AttributeLogicalNameAttribute("sdkmessageresponseid")]
		public virtual Guid SdkMessageResponseId
		{
			get { return this.GetAttributeValue<Guid>("sdkmessageresponseid"); }
			set { this.SetAttributeValue("sdkmessageresponseid", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessageresponseidunique")]
		public virtual object SdkMessageResponseIdUnique
		{
			get { return this.GetAttributeValue<object>("sdkmessageresponseidunique"); }
		}
		[AttributeLogicalNameAttribute("solutionid")]
		public virtual object SolutionId
		{
			get { return this.GetAttributeValue<object>("solutionid"); }
		}
		[AttributeLogicalNameAttribute("supportingsolutionid")]
		public virtual object SupportingSolutionId
		{
			get { return this.GetAttributeValue<object>("supportingsolutionid"); }
		}
		[AttributeLogicalNameAttribute("versionnumber")]
		public virtual int? VersionNumber
		{
			get { return this.GetAttributeValue<int?>("versionnumber"); }
		}
	}
}
