// 
// Code generated by a template.
//
using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;

namespace CCLLC.CDS.Sdk.Metadata.Proxy 
{
	[EntityLogicalName("sdkmessage")]
	public partial class SdkMessage : Entity
	{
		public static string EntityLogicalName => "sdkmessage";

		public SdkMessage()
			: base("sdkmessage") {}


		#region Late Bound Field Constants
	
		public class Fields
		{			
			public const string Id = "sdkmessageid";
			public const string AutoTransact = "autotransact";
			public const string AutoTransactName = "autotransactname";
			public const string Availability = "availability";
			public const string CategoryName = "categoryname";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CustomizationLevel = "customizationlevel";
			public const string Expand = "expand";
			public const string ExpandName = "expandname";
			public const string IntroducedVersion = "introducedversion";
			public const string IsActive = "isactive";
			public const string IsActiveName = "isactivename";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string IsPrivate = "isprivate";
			public const string IsPrivateName = "isprivatename";
			public const string IsReadOnly = "isreadonly";
			public const string IsReadOnlyName = "isreadonlyname";
			public const string IsValidForExecuteAsync = "isvalidforexecuteasync";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string SdkMessageId = "sdkmessageid";
			public const string SdkMessageIdUnique = "sdkmessageidunique";
			public const string SolutionId = "solutionid";
			public const string SupportingSolutionId = "supportingsolutionid";
			public const string Template = "template";
			public const string TemplateName = "templatename";
			public const string ThrottleSettings = "throttlesettings";
			public const string VersionNumber = "versionnumber";
			public const string WorkflowSdkStepEnabled = "workflowsdkstepenabled";
			public const string WorkflowSdkStepEnabledName = "workflowsdkstepenabledname";
		}

		#endregion

		[AttributeLogicalName("sdkmessageid")]
		public override Guid Id
		{
			get => base.Id; 
			set => SdkMessageId = value;
		}

		[AttributeLogicalName("autotransact")]
		public virtual bool? AutoTransact
		{
			get => GetAttributeValue<bool>("autotransact"); 
			set => SetAttributeValue("autotransact", value); 
		}
		[AttributeLogicalName("autotransactname")]
		public virtual string AutoTransactName
		{
			get => GetAttributeValue<string>("autotransactname"); 
		}
		[AttributeLogicalName("availability")]
		public virtual int? Availability
		{
			get => GetAttributeValue<int>("availability"); 
			set => SetAttributeValue("availability", value); 
		}
		[AttributeLogicalName("categoryname")]
		public virtual string CategoryName
		{
			get => GetAttributeValue<string>("categoryname"); 
			set => SetAttributeValue("categoryname", value); 
		}
		[AttributeLogicalName("componentstate")]
		public virtual GlobalEnums.eComponentstate? ComponentState
		{
			get 
			{
				var value = GetAttributeValue<OptionSetValue>("componentstate"); 
				if(value is null) return null;
				return (GlobalEnums.eComponentstate?)value.Value;
			}
		}
		[AttributeLogicalName("createdby")]
		public virtual EntityReference CreatedBy
		{
			get => GetAttributeValue<EntityReference>("createdby"); 
		}
		[AttributeLogicalName("createdbyname")]
		public virtual string CreatedByName
		{
			get => GetAttributeValue<string>("createdbyname"); 
		}
		[AttributeLogicalName("createdon")]
		public virtual DateTime? CreatedOn
		{
			get => GetAttributeValue<DateTime>("createdon"); 
		}
		[AttributeLogicalName("createdonbehalfby")]
		public virtual EntityReference CreatedOnBehalfBy
		{
			get => GetAttributeValue<EntityReference>("createdonbehalfby"); 
		}
		[AttributeLogicalName("createdonbehalfbyname")]
		public virtual string CreatedOnBehalfByName
		{
			get => GetAttributeValue<string>("createdonbehalfbyname"); 
		}
		[AttributeLogicalName("createdonbehalfbyyominame")]
		public virtual string CreatedOnBehalfByYomiName
		{
			get => GetAttributeValue<string>("createdonbehalfbyyominame"); 
		}
		[AttributeLogicalName("customizationlevel")]
		public virtual int? CustomizationLevel
		{
			get => GetAttributeValue<int>("customizationlevel"); 
		}
		[AttributeLogicalName("expand")]
		public virtual bool? Expand
		{
			get => GetAttributeValue<bool>("expand"); 
			set => SetAttributeValue("expand", value); 
		}
		[AttributeLogicalName("expandname")]
		public virtual string ExpandName
		{
			get => GetAttributeValue<string>("expandname"); 
		}
		[AttributeLogicalName("introducedversion")]
		public virtual string IntroducedVersion
		{
			get => GetAttributeValue<string>("introducedversion"); 
			set => SetAttributeValue("introducedversion", value); 
		}
		[AttributeLogicalName("isactive")]
		public virtual bool? IsActive
		{
			get => GetAttributeValue<bool>("isactive"); 
			set => SetAttributeValue("isactive", value); 
		}
		[AttributeLogicalName("isactivename")]
		public virtual string IsActiveName
		{
			get => GetAttributeValue<string>("isactivename"); 
		}
		[AttributeLogicalName("ismanaged")]
		public virtual bool? IsManaged
		{
			get => GetAttributeValue<bool>("ismanaged"); 
		}
		[AttributeLogicalName("ismanagedname")]
		public virtual string IsManagedName
		{
			get => GetAttributeValue<string>("ismanagedname"); 
		}
		[AttributeLogicalName("isprivate")]
		public virtual bool? IsPrivate
		{
			get => GetAttributeValue<bool>("isprivate"); 
			set => SetAttributeValue("isprivate", value); 
		}
		[AttributeLogicalName("isprivatename")]
		public virtual string IsPrivateName
		{
			get => GetAttributeValue<string>("isprivatename"); 
		}
		[AttributeLogicalName("isreadonly")]
		public virtual bool? IsReadOnly
		{
			get => GetAttributeValue<bool>("isreadonly"); 
			set => SetAttributeValue("isreadonly", value); 
		}
		[AttributeLogicalName("isreadonlyname")]
		public virtual string IsReadOnlyName
		{
			get => GetAttributeValue<string>("isreadonlyname"); 
		}
		[AttributeLogicalName("isvalidforexecuteasync")]
		public virtual bool? IsValidForExecuteAsync
		{
			get => GetAttributeValue<bool>("isvalidforexecuteasync"); 
		}
		[AttributeLogicalName("modifiedby")]
		public virtual EntityReference ModifiedBy
		{
			get => GetAttributeValue<EntityReference>("modifiedby"); 
		}
		[AttributeLogicalName("modifiedbyname")]
		public virtual string ModifiedByName
		{
			get => GetAttributeValue<string>("modifiedbyname"); 
		}
		[AttributeLogicalName("modifiedon")]
		public virtual DateTime? ModifiedOn
		{
			get => GetAttributeValue<DateTime>("modifiedon"); 
		}
		[AttributeLogicalName("modifiedonbehalfby")]
		public virtual EntityReference ModifiedOnBehalfBy
		{
			get => GetAttributeValue<EntityReference>("modifiedonbehalfby"); 
		}
		[AttributeLogicalName("modifiedonbehalfbyname")]
		public virtual string ModifiedOnBehalfByName
		{
			get => GetAttributeValue<string>("modifiedonbehalfbyname"); 
		}
		[AttributeLogicalName("modifiedonbehalfbyyominame")]
		public virtual string ModifiedOnBehalfByYomiName
		{
			get => GetAttributeValue<string>("modifiedonbehalfbyyominame"); 
		}
		[AttributeLogicalName("name")]
		public virtual string Name
		{
			get => GetAttributeValue<string>("name"); 
			set => SetAttributeValue("name", value); 
		}
		[AttributeLogicalName("organizationid")]
		public virtual EntityReference OrganizationId
		{
			get => GetAttributeValue<EntityReference>("organizationid"); 
		}
		[AttributeLogicalName("overwritetime")]
		public virtual DateTime? OverwriteTime
		{
			get => GetAttributeValue<DateTime>("overwritetime"); 
		}
		[AttributeLogicalName("sdkmessageid")]
		public virtual Guid SdkMessageId
		{
			get => GetAttributeValue<Guid>("sdkmessageid"); 
			set => SetAttributeValue("sdkmessageid", value); 
		}
		[AttributeLogicalName("sdkmessageidunique")]
		public virtual object SdkMessageIdUnique
		{
			get => GetAttributeValue<object>("sdkmessageidunique"); 
		}
		[AttributeLogicalName("solutionid")]
		public virtual object SolutionId
		{
			get => GetAttributeValue<object>("solutionid"); 
		}
		[AttributeLogicalName("supportingsolutionid")]
		public virtual object SupportingSolutionId
		{
			get => GetAttributeValue<object>("supportingsolutionid"); 
		}
		[AttributeLogicalName("template")]
		public virtual bool? Template
		{
			get => GetAttributeValue<bool>("template"); 
			set => SetAttributeValue("template", value); 
		}
		[AttributeLogicalName("templatename")]
		public virtual string TemplateName
		{
			get => GetAttributeValue<string>("templatename"); 
		}
		[AttributeLogicalName("throttlesettings")]
		public virtual string ThrottleSettings
		{
			get => GetAttributeValue<string>("throttlesettings"); 
		}
		[AttributeLogicalName("versionnumber")]
		public virtual int? VersionNumber
		{
			get => GetAttributeValue<int>("versionnumber"); 
		}
		[AttributeLogicalName("workflowsdkstepenabled")]
		public virtual bool? WorkflowSdkStepEnabled
		{
			get => GetAttributeValue<bool>("workflowsdkstepenabled"); 
		}
		[AttributeLogicalName("workflowsdkstepenabledname")]
		public virtual string WorkflowSdkStepEnabledName
		{
			get => GetAttributeValue<string>("workflowsdkstepenabledname"); 
		}
	}
}
