// 
// Code generated by a template.
//
using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;

namespace CCLLC.CDS.Sdk.Metadata.Proxy 
{

	[EntityLogicalNameAttribute("sdkmessagefilter")]
	public partial class SdkMessageFilter : Entity
	{
		public static string EntityLogicalName => "sdkmessagefilter";

		public SdkMessageFilter()
			: base("sdkmessagefilter")
		{
		}

		#region Late Bound Fields
	
		public class Fields
		{			
			public const string Id = "sdkmessagefilterid";
			public const string Availability = "availability";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CustomizationLevel = "customizationlevel";
			public const string IntroducedVersion = "introducedversion";
			public const string IsCustomProcessingStepAllowed = "iscustomprocessingstepallowed";
			public const string IsCustomProcessingStepAllowedName = "iscustomprocessingstepallowedname";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string IsVisible = "isvisible";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string PrimaryObjectTypeCodeName = "primaryobjecttypecodename";
			public const string RestrictionLevel = "restrictionlevel";
			public const string SdkMessageFilterId = "sdkmessagefilterid";
			public const string SdkMessageFilterIdUnique = "sdkmessagefilteridunique";
			public const string SdkMessageId = "sdkmessageid";
			public const string SdkMessageIdName = "sdkmessageidname";
			public const string SecondaryObjectTypeCodeName = "secondaryobjecttypecodename";
			public const string SolutionId = "solutionid";
			public const string SupportingSolutionId = "supportingsolutionid";
			public const string VersionNumber = "versionnumber";
			public const string WorkflowSdkStepEnabled = "workflowsdkstepenabled";
			public const string WorkflowSdkStepEnabledName = "workflowsdkstepenabledname";
		}

		#endregion

		[AttributeLogicalNameAttribute("sdkmessagefilterid")]
		public override Guid Id
		{
			get { return base.Id; }
			set { SdkMessageFilterId = value; }
		}

		[AttributeLogicalNameAttribute("availability")]
		public virtual int? Availability
		{
			get { return this.GetAttributeValue<int?>("availability"); }
			set { this.SetAttributeValue("availability", value); }
		}
		[AttributeLogicalNameAttribute("componentstate")]
		public virtual OptionSetValue ComponentState
		{
			get { return this.GetAttributeValue<OptionSetValue>("componentstate"); }
		}
		[AttributeLogicalNameAttribute("createdby")]
		public virtual EntityReference CreatedBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdby"); }
		}
		[AttributeLogicalNameAttribute("createdbyname")]
		public virtual string CreatedByName
		{
			get { return this.GetAttributeValue<string>("createdbyname"); }
		}
		[AttributeLogicalNameAttribute("createdon")]
		public virtual DateTime? CreatedOn
		{
			get { return this.GetAttributeValue<DateTime?>("createdon"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfby")]
		public virtual EntityReference CreatedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public virtual string CreatedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public virtual string CreatedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("customizationlevel")]
		public virtual int? CustomizationLevel
		{
			get { return this.GetAttributeValue<int?>("customizationlevel"); }
		}
		[AttributeLogicalNameAttribute("introducedversion")]
		public virtual string IntroducedVersion
		{
			get { return this.GetAttributeValue<string>("introducedversion"); }
			set { this.SetAttributeValue("introducedversion", value); }
		}
		[AttributeLogicalNameAttribute("iscustomprocessingstepallowed")]
		public virtual bool? IsCustomProcessingStepAllowed
		{
			get { return this.GetAttributeValue<bool?>("iscustomprocessingstepallowed"); }
			set { this.SetAttributeValue("iscustomprocessingstepallowed", value); }
		}
		[AttributeLogicalNameAttribute("iscustomprocessingstepallowedname")]
		public virtual string IsCustomProcessingStepAllowedName
		{
			get { return this.GetAttributeValue<string>("iscustomprocessingstepallowedname"); }
		}
		[AttributeLogicalNameAttribute("ismanaged")]
		public virtual bool? IsManaged
		{
			get { return this.GetAttributeValue<bool?>("ismanaged"); }
		}
		[AttributeLogicalNameAttribute("ismanagedname")]
		public virtual string IsManagedName
		{
			get { return this.GetAttributeValue<string>("ismanagedname"); }
		}
		[AttributeLogicalNameAttribute("isvisible")]
		public virtual bool? IsVisible
		{
			get { return this.GetAttributeValue<bool?>("isvisible"); }
		}
		[AttributeLogicalNameAttribute("modifiedby")]
		public virtual EntityReference ModifiedBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedby"); }
		}
		[AttributeLogicalNameAttribute("modifiedbyname")]
		public virtual string ModifiedByName
		{
			get { return this.GetAttributeValue<string>("modifiedbyname"); }
		}
		[AttributeLogicalNameAttribute("modifiedon")]
		public virtual DateTime? ModifiedOn
		{
			get { return this.GetAttributeValue<DateTime?>("modifiedon"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public virtual EntityReference ModifiedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public virtual string ModifiedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public virtual string ModifiedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("organizationid")]
		public virtual EntityReference OrganizationId
		{
			get { return this.GetAttributeValue<EntityReference>("organizationid"); }
		}
		[AttributeLogicalNameAttribute("overwritetime")]
		public virtual DateTime? OverwriteTime
		{
			get { return this.GetAttributeValue<DateTime?>("overwritetime"); }
		}
		[AttributeLogicalNameAttribute("primaryobjecttypecodename")]
		public virtual string PrimaryObjectTypeCodeName
		{
			get { return this.GetAttributeValue<string>("primaryobjecttypecodename"); }
		}
		[AttributeLogicalNameAttribute("restrictionlevel")]
		public virtual int? RestrictionLevel
		{
			get { return this.GetAttributeValue<int?>("restrictionlevel"); }
			set { this.SetAttributeValue("restrictionlevel", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessagefilterid")]
		public virtual Guid SdkMessageFilterId
		{
			get { return this.GetAttributeValue<Guid>("sdkmessagefilterid"); }
			set { this.SetAttributeValue("sdkmessagefilterid", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessagefilteridunique")]
		public virtual object SdkMessageFilterIdUnique
		{
			get { return this.GetAttributeValue<object>("sdkmessagefilteridunique"); }
		}
		[AttributeLogicalNameAttribute("sdkmessageid")]
		public virtual EntityReference SdkMessageId
		{
			get { return this.GetAttributeValue<EntityReference>("sdkmessageid"); }
			set { this.SetAttributeValue("sdkmessageid", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessageidname")]
		public virtual string SdkMessageIdName
		{
			get { return this.GetAttributeValue<string>("sdkmessageidname"); }
		}
		[AttributeLogicalNameAttribute("secondaryobjecttypecodename")]
		public virtual string SecondaryObjectTypeCodeName
		{
			get { return this.GetAttributeValue<string>("secondaryobjecttypecodename"); }
		}
		[AttributeLogicalNameAttribute("solutionid")]
		public virtual object SolutionId
		{
			get { return this.GetAttributeValue<object>("solutionid"); }
		}
		[AttributeLogicalNameAttribute("supportingsolutionid")]
		public virtual object SupportingSolutionId
		{
			get { return this.GetAttributeValue<object>("supportingsolutionid"); }
		}
		[AttributeLogicalNameAttribute("versionnumber")]
		public virtual int? VersionNumber
		{
			get { return this.GetAttributeValue<int?>("versionnumber"); }
		}
		[AttributeLogicalNameAttribute("workflowsdkstepenabled")]
		public virtual bool? WorkflowSdkStepEnabled
		{
			get { return this.GetAttributeValue<bool?>("workflowsdkstepenabled"); }
		}
		[AttributeLogicalNameAttribute("workflowsdkstepenabledname")]
		public virtual string WorkflowSdkStepEnabledName
		{
			get { return this.GetAttributeValue<string>("workflowsdkstepenabledname"); }
		}
	}
}
