// 
// Code generated by a template.
//
using System;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Client;

namespace CCLLC.CDS.Sdk.Metadata.Proxy 
{

	[EntityLogicalNameAttribute("sdkmessagerequestfield")]
	public partial class SdkMessageRequestField : Entity
	{
		public static string EntityLogicalName => "sdkmessagerequestfield";

		public SdkMessageRequestField()
			: base("sdkmessagerequestfield")
		{
		}

		#region Late Bound Fields
	
		public class Fields
		{			
			public const string Id = "sdkmessagerequestfieldid";
			public const string ClrParser = "clrparser";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string CustomizationLevel = "customizationlevel";
			public const string FieldMask = "fieldmask";
			public const string IntroducedVersion = "introducedversion";
			public const string IsManaged = "ismanaged";
			public const string IsManagedName = "ismanagedname";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string Name = "name";
			public const string Optional = "optional";
			public const string OrganizationId = "organizationid";
			public const string OverwriteTime = "overwritetime";
			public const string ParameterBindingInformation = "parameterbindinginformation";
			public const string Parser = "parser";
			public const string Position = "position";
			public const string PublicName = "publicname";
			public const string SdkMessageRequestFieldId = "sdkmessagerequestfieldid";
			public const string SdkMessageRequestFieldIdUnique = "sdkmessagerequestfieldidunique";
			public const string SdkMessageRequestId = "sdkmessagerequestid";
			public const string SolutionId = "solutionid";
			public const string SupportingSolutionId = "supportingsolutionid";
			public const string VersionNumber = "versionnumber";
		}

		#endregion

		[AttributeLogicalNameAttribute("sdkmessagerequestfieldid")]
		public override Guid Id
		{
			get { return base.Id; }
			set { SdkMessageRequestFieldId = value; }
		}

		[AttributeLogicalNameAttribute("clrparser")]
		public virtual string ClrParser
		{
			get { return this.GetAttributeValue<string>("clrparser"); }
			set { this.SetAttributeValue("clrparser", value); }
		}
		[AttributeLogicalNameAttribute("componentstate")]
		public virtual OptionSetValue ComponentState
		{
			get { return this.GetAttributeValue<OptionSetValue>("componentstate"); }
		}
		[AttributeLogicalNameAttribute("createdby")]
		public virtual EntityReference CreatedBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdby"); }
		}
		[AttributeLogicalNameAttribute("createdon")]
		public virtual DateTime? CreatedOn
		{
			get { return this.GetAttributeValue<DateTime?>("createdon"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfby")]
		public virtual EntityReference CreatedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("createdonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public virtual string CreatedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public virtual string CreatedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("createdonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("customizationlevel")]
		public virtual int? CustomizationLevel
		{
			get { return this.GetAttributeValue<int?>("customizationlevel"); }
		}
		[AttributeLogicalNameAttribute("fieldmask")]
		public virtual int? FieldMask
		{
			get { return this.GetAttributeValue<int?>("fieldmask"); }
		}
		[AttributeLogicalNameAttribute("introducedversion")]
		public virtual string IntroducedVersion
		{
			get { return this.GetAttributeValue<string>("introducedversion"); }
			set { this.SetAttributeValue("introducedversion", value); }
		}
		[AttributeLogicalNameAttribute("ismanaged")]
		public virtual bool? IsManaged
		{
			get { return this.GetAttributeValue<bool?>("ismanaged"); }
		}
		[AttributeLogicalNameAttribute("ismanagedname")]
		public virtual string IsManagedName
		{
			get { return this.GetAttributeValue<string>("ismanagedname"); }
		}
		[AttributeLogicalNameAttribute("modifiedby")]
		public virtual EntityReference ModifiedBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedby"); }
		}
		[AttributeLogicalNameAttribute("modifiedon")]
		public virtual DateTime? ModifiedOn
		{
			get { return this.GetAttributeValue<DateTime?>("modifiedon"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public virtual EntityReference ModifiedOnBehalfBy
		{
			get { return this.GetAttributeValue<EntityReference>("modifiedonbehalfby"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public virtual string ModifiedOnBehalfByName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyname"); }
		}
		[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public virtual string ModifiedOnBehalfByYomiName
		{
			get { return this.GetAttributeValue<string>("modifiedonbehalfbyyominame"); }
		}
		[AttributeLogicalNameAttribute("name")]
		public virtual string Name
		{
			get { return this.GetAttributeValue<string>("name"); }
			set { this.SetAttributeValue("name", value); }
		}
		[AttributeLogicalNameAttribute("optional")]
		public virtual bool? Optional
		{
			get { return this.GetAttributeValue<bool?>("optional"); }
			set { this.SetAttributeValue("optional", value); }
		}
		[AttributeLogicalNameAttribute("organizationid")]
		public virtual EntityReference OrganizationId
		{
			get { return this.GetAttributeValue<EntityReference>("organizationid"); }
		}
		[AttributeLogicalNameAttribute("overwritetime")]
		public virtual DateTime? OverwriteTime
		{
			get { return this.GetAttributeValue<DateTime?>("overwritetime"); }
		}
		[AttributeLogicalNameAttribute("parameterbindinginformation")]
		public virtual string ParameterBindingInformation
		{
			get { return this.GetAttributeValue<string>("parameterbindinginformation"); }
			set { this.SetAttributeValue("parameterbindinginformation", value); }
		}
		[AttributeLogicalNameAttribute("parser")]
		public virtual string Parser
		{
			get { return this.GetAttributeValue<string>("parser"); }
			set { this.SetAttributeValue("parser", value); }
		}
		[AttributeLogicalNameAttribute("position")]
		public virtual int? Position
		{
			get { return this.GetAttributeValue<int?>("position"); }
		}
		[AttributeLogicalNameAttribute("publicname")]
		public virtual string PublicName
		{
			get { return this.GetAttributeValue<string>("publicname"); }
			set { this.SetAttributeValue("publicname", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessagerequestfieldid")]
		public virtual Guid SdkMessageRequestFieldId
		{
			get { return this.GetAttributeValue<Guid>("sdkmessagerequestfieldid"); }
			set { this.SetAttributeValue("sdkmessagerequestfieldid", value); }
		}
		[AttributeLogicalNameAttribute("sdkmessagerequestfieldidunique")]
		public virtual object SdkMessageRequestFieldIdUnique
		{
			get { return this.GetAttributeValue<object>("sdkmessagerequestfieldidunique"); }
		}
		[AttributeLogicalNameAttribute("sdkmessagerequestid")]
		public virtual EntityReference SdkMessageRequestId
		{
			get { return this.GetAttributeValue<EntityReference>("sdkmessagerequestid"); }
		}
		[AttributeLogicalNameAttribute("solutionid")]
		public virtual object SolutionId
		{
			get { return this.GetAttributeValue<object>("solutionid"); }
		}
		[AttributeLogicalNameAttribute("supportingsolutionid")]
		public virtual object SupportingSolutionId
		{
			get { return this.GetAttributeValue<object>("supportingsolutionid"); }
		}
		[AttributeLogicalNameAttribute("versionnumber")]
		public virtual int? VersionNumber
		{
			get { return this.GetAttributeValue<int?>("versionnumber"); }
		}
	}
}
